# Generated by Django 3.1.3 on 2020-12-11 19:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=150)),
                ('gearType', models.CharField(max_length=100, verbose_name='Gear Type')),
                ('fuelType', models.CharField(max_length=100, verbose_name='Fuel Type')),
                ('isReserved', models.BooleanField(default=False, verbose_name='Reserved')),
                ('isActive', models.BooleanField(default=True, verbose_name='Active')),
                ('buyingDate', models.DateTimeField(auto_now_add=True, verbose_name='Purchase date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('takeDate', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('returnDate', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), blank=True, null=True, size=None)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservations.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, choices=[('manager', 'Manager'), ('admin', 'Admin'), ('customer', 'Customer')], max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservations.visitor'),
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('receiveDate', models.DateTimeField(blank=True, null=True, verbose_name='Receive Date')),
                ('deliveryDate', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservations.visitor', verbose_name='Buyer')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservations.car', verbose_name='Car')),
            ],
            options={
                'unique_together': {('buyer', 'car')},
            },
        ),
    ]
