# Generated by Django 3.1.3 on 2020-12-21 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0002_visitor_profile_pic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservations',
            unique_together=set(),
        ),
    ]
