# Generated by Django 3.1.4 on 2020-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0003_auto_20201221_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, default='wp.png', upload_to='media'),
        ),
    ]
