# Generated by Django 3.1.4 on 2020-12-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0004_auto_20201231_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuelType',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=100, verbose_name='Fuel Type'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearType',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Semi-Automatic', 'Semi-Automatic'), ('Manuel', 'Manuel')], max_length=100, verbose_name='Gear Type'),
        ),
    ]
