# Generated by Django 3.1.4 on 2021-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservations', '0005_auto_20201231_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='adress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='fax',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
